version: "3.3"

services:

  api:
    build:
      context: server
    image: server
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    labels:
      - traefik.docker.network=traefik_default
      - traefik.http.routers.api-gw.rule=Host(`bonds-filter.local`)
      - traefik.http.routers.api-gw.entrypoints=web,websecure
      - traefik.http.services.api.loadbalancer.server.port=3000
    networks:
      - internal
      - traefik_default

#  greeter:
#    build:
#      context: server
#    image: server
#    env_file: docker-compose.env
#    environment:
#      SERVICES: greeter
#    depends_on:
#      - api
#    networks:
#      - internal


networks:
  internal:
  traefik_default:
    external: true

volumes:
  data:
