services:

  backend:
    build:
      context: .
      dockerfile: server.Dockerfile
    image: bonds-filter-tinkoff-api
    env_file: ./server/.env
    #    environment:
    #      SERVICES: api
    #      PORT: 3000
    volumes:
      - ./server/.cache:/app/.cache
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_net
      - traefik.http.routers.bonds-filter-backend.rule=Host(`bonds-filter.local`) && PathPrefix(`/api`)
      - traefik.http.routers.bonds-filter-backend.entrypoints=web
      - traefik.http.services.bonds-filter-backend.loadbalancer.server.port=3000
    networks:
      - traefik_net

  frontend:
    build:
      context: .
      dockerfile: ui.Dockerfile
    image: bonds-filter-tinkoff-ui
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_net
      - traefik.http.routers.bonds-filter-frontend.rule=Host(`bonds-filter.local`)
      - traefik.http.routers.bonds-filter-frontend.entrypoints=web
      - traefik.http.services.bonds-filter-frontend.loadbalancer.server.port=80
    networks:
      - traefik_net

#  greeter:
#    build:
#      context: server
#    image: server
#    env_file: docker-compose.env
#    environment:
#      SERVICES: greeter
#    depends_on:
#      - api
#    networks:
#      - internal


networks:
  traefik_net:
    external: true

volumes:
  data:
