/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/UI/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/UI/BaseSide.vue')['default']
    BondFlags: typeof import('./components/UI/BondFlags.vue')['default']
    BondOptionsChecks: typeof import('./components/UI/BondOptionsChecks.vue')['default']
    BondOptionsRadios: typeof import('./components/UI/BondOptionsRadios.vue')['default']
    BondOptionsSelect: typeof import('./components/UI/BondOptionsSelect.vue')['default']
    BondsFilter: typeof import('./components/BondsFilter.vue')['default']
    BondsTable: typeof import('./components/BondsTable.vue')['default']
    ElCheckboxButton: typeof import('element-plus/es')['ElCheckboxButton']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    IconNewWindow: typeof import('./components/icons/IconNewWindow.vue')['default']
    LinksToExchange: typeof import('./components/UI/LinksToExchange.vue')['default']
    LiquidityArrow: typeof import('./components/UI/LiquidityArrow.vue')['default']
    LoadingOverlay: typeof import('./components/UI/LoadingOverlay.vue')['default']
    RiskStars: typeof import('./components/UI/RiskStars.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
