const tsParser = require("@typescript-eslint/parser")
const tsPlugin = require("@typescript-eslint/eslint-plugin")
const importPlugin = require("eslint-plugin-import")
const preferArrowPlugin = require("eslint-plugin-prefer-arrow")

module.exports = [
	{
		ignores: ["dist/*", "node_modules/*"],
	},
	{
		files: ["**/*.js", "**/*.ts"],
		languageOptions: {
			ecmaVersion: 2018,
			sourceType: "module",
			parser: tsParser,
			parserOptions: {
				project: "tsconfig.json",
			},
			globals: {
				console: "readonly",
				module: "readonly",
				process: "readonly",
				require: "readonly",
				__dirname: "readonly",
				__filename: "readonly",
			},
		},
		plugins: {
			"@typescript-eslint": tsPlugin,
			import: importPlugin,
			"prefer-arrow": preferArrowPlugin,
		},
		rules: {
			"@typescript-eslint/adjacent-overload-signatures": "error",
			"@typescript-eslint/array-type": "error",
			"@typescript-eslint/ban-ts-comment": "off",
			"@typescript-eslint/consistent-type-assertions": "error",
			"@typescript-eslint/consistent-type-definitions": "error",
			"@typescript-eslint/explicit-member-accessibility": [
				"off",
				{
					accessibility: "explicit",
				},
			],
			"@typescript-eslint/member-ordering": "error",
			"@typescript-eslint/no-empty-function": "error",
			"@typescript-eslint/no-empty-interface": "error",
			"@typescript-eslint/no-explicit-any": "off",
			"@typescript-eslint/no-misused-new": "error",
			"@typescript-eslint/no-namespace": "error",
			"@typescript-eslint/no-use-before-define": "off",
			"@typescript-eslint/no-var-requires": "error",
			"@typescript-eslint/prefer-for-of": "error",
			"@typescript-eslint/prefer-function-type": "error",
			"@typescript-eslint/prefer-namespace-keyword": "error",
			"@typescript-eslint/triple-slash-reference": "error",
			"@typescript-eslint/unified-signatures": "error",
			"arrow-body-style": "error",
			"arrow-parens": ["error", "as-needed"],
			camelcase: "error",
			"comma-dangle": ["error", "always-multiline"],
			complexity: "off",
			"constructor-super": "error",
			curly: "off",
			"dot-notation": "error",
			"eol-last": "error",
			eqeqeq: ["error", "smart"],
			"guard-for-in": "error",
			"id-blacklist": ["error", "any", "Number", "number", "String", "string", "Boolean", "boolean", "Undefined", "undefined"],
			"id-match": "error",
			"import/order": "error",
			"max-classes-per-file": ["error", 1],
			"max-len": [
				"error",
				{
					ignoreUrls: true,
					code: 160,
				},
			],
			"new-parens": "error",
			"no-bitwise": "error",
			"no-caller": "error",
			"no-cond-assign": "error",
			"no-console": "off",
			"no-debugger": "error",
			"no-empty": "error",
			"no-eval": "error",
			"no-fallthrough": "off",
			"no-invalid-this": "off",
			"no-multiple-empty-lines": "error",
			"no-new-wrappers": "error",
			"no-shadow": "off",
			"@typescript-eslint/no-shadow": "warn",
			"no-throw-literal": "error",
			"no-trailing-spaces": "error",
			"no-undef-init": "error",
			"no-underscore-dangle": "off",
			"no-unsafe-finally": "error",
			"no-unused-expressions": "error",
			"no-unused-labels": "error",
			"no-var": "error",
			"object-shorthand": "error",
			"one-var": ["error", "never"],
			"prefer-arrow/prefer-arrow-functions": "off",
			"prefer-const": "error",
			quotes: [
				"error",
				"double",
				{
					avoidEscape: true,
				},
			],
			"quote-props": ["error", "as-needed"],
			radix: "error",
			semi: ["error", "never"],
			"space-before-function-paren": [
				"error",
				{
					anonymous: "never",
					asyncArrow: "always",
					named: "never",
				},
			],
			"spaced-comment": "error",
			"use-isnan": "error",
			"valid-typeof": "off",
		},
	},
]
